learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('learning_logs.urls',namespace='learning_logs')),
]

learning_logs/urls.py
# define the url of the learning_logs 

from django.conf.urls import url
from . import views

urlpatterns=[url(r'^$',views.index,name='index'),]

learning_logs/models.py
from django.db import models

# Create your models here.
# here for test models

class Topic(models.Model):
	text=models.CharField(max_length=200)
	data_added=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.text
class Entry(models.Model):
	topic=models.ForeignKey(Topic)
	text=models.TextField()
	data_added=models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural='entries'
		
	def __str__(self):
		return self.text[:50] +"....."

learning_logs/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	# "the homepage of the webapp"
	return render(request,'learning_logs/index.html')
	

learning_logs/templates/learning_logs/base.html
<p>
	<a>herf="{% url 'learning_logs:index' %}"> learning log</a>
</p>

{% block content %}{%endblock content%}

learning_logs/templates/learning_logs/index.html
{% estends "learning_blogs/bases.html" %}

{% block content %}
	<p> learning_logs</p>
	<p>learning log help you keep track of ypur learning ,for any topic you are learning about,</p>
{% endblock content %}